apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name 
  namespace: 
  labels: &labels
    app.kubernetes.io/name: *name
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
      - name: *name
        image: 
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 
            memory: 
          limits:
            cpu: 
            memory: 
        command:
        - null
        args:
        - null
        ports:
        - name: &port 
          protocol: TCP
          containerPort: 
        volumeMounts:
        - name: 
          mountPath: 
        startupProbe:
          tcpSocket:
            port: *port
          initialDelaySeconds: 
          timeoutSeconds: 
          periodSeconds: 
          successThreshold: 
          failureThreshold: 
        livenessProbe:
          tcpSocket:
            port: *port
          initialDelaySeconds: 
          timeoutSeconds: 
          periodSeconds: 
          successThreshold: 
          failureThreshold: 
        readinessProbe:
          tcpSocket:
            port: *port
          initialDelaySeconds: 
          timeoutSeconds: 
          periodSeconds: 
          successThreshold: 
          failureThreshold: 
        env:
        - name: 
          value: 
      volumes:
      - name: 
        persistentVolumeClaim:
          claimName: 
