k9s:
  refreshRate: 1
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  skipLatestRevCheck: false
  logger:
    tail: 500
    buffer: 5000
    sinceSeconds: -1
    fullScreenLogs: false
    textWrap: true
    showTime: false
  currentContext: test-dev
  currentCluster: arn:aws:eks:us-east-1:419660905811:cluster/test-dev
  clusters:
    default:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - default
        - argocd
        - karpenter
        - kube-system
        - prometheus
      view:
        active: deploy
      featureGates:
        nodeShell: true
      shellPod:
        image: nicolaka/netshoot:latest
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: 0.0.0.0    
    arn:aws:eks:us-east-1:419660905811:cluster/test-dev:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - default
        - argocd
        - karpenter
        - kube-system
        - prometheus
      view:
        active: deploy
      featureGates:
        nodeShell: true
      shellPod:
        image: nicolaka/netshoot:latest
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: 0.0.0.0
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /tmp/k9s-screens
